package Interface.StudentRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.FacilityEnterprise;
import Business.Facility.Basketball.BasketballCourtAvailability;
import Business.Network.Network;
import Business.ThatsMyPlaceSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import javax.swing.JPanel;

/**
 *
 * @author Karti
 * @author Bochao
 */
public class StudentHomePageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentHomePageJPanel
     */
    private JPanel rightPanel;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private ThatsMyPlaceSystem business;
    
    private HashSet<LocalDate> availableDates;
    
    public StudentHomePageJPanel(JPanel rightPanel, 
            UserAccount userAccount, 
            Enterprise enterprise, 
            ThatsMyPlaceSystem business) 
    {
        initComponents();
        this.rightPanel = rightPanel;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business = business;
        this.availableDates = new HashSet<>();
        
        populate();  // populate the combo box
        
        btnBookingHistory.setContentAreaFilled(false);
        btnMakeBooking.setContentAreaFilled(false);
    }
    
    private void populate() {
        FacilityEnterprise facilityEnterprise = null;
        for (Network network: business.getNetworkList()) {
            for (Enterprise e: network.getEnterpriseDirectory().getEnterpriseList()) {
                if (e.getEnterpriseType().equals(Enterprise.EnterpriseType.Facility)) {
                    facilityEnterprise = (FacilityEnterprise) e;
                    break;
                }
            }
            if (facilityEnterprise != null) break;
        }
        
        if (facilityEnterprise != null) {
            ArrayList<BasketballCourtAvailability> availabilityList = (ArrayList) facilityEnterprise.getBasketballCourtAvailDirectory().getList();
            for (BasketballCourtAvailability availability: availabilityList) {
                availableDates.add(availability.getDate());
            }
            ArrayList<LocalDate> localDateList = new ArrayList<>(availableDates);
            Collections.sort(localDateList);
            for (LocalDate localDate: localDateList) {
                cbNumberOfPeople.addItem(localDate.toString());
            }
        }
        else {
            System.out.println("Error!!!");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBookingHistory = new javax.swing.JButton();
        btnMakeBooking = new javax.swing.JButton();
        lblStudentHomePage = new javax.swing.JLabel();
        cbNumberOfPeople = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 700));

        btnBookingHistory.setBackground(new java.awt.Color(45, 118, 232));
        btnBookingHistory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBookingHistory.setForeground(new java.awt.Color(45, 118, 232));
        btnBookingHistory.setText("BOOKING HISTORY");
        btnBookingHistory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        btnBookingHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingHistoryActionPerformed(evt);
            }
        });

        btnMakeBooking.setBackground(new java.awt.Color(45, 118, 232));
        btnMakeBooking.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMakeBooking.setForeground(new java.awt.Color(45, 118, 232));
        btnMakeBooking.setText("MAKE BOOKING");
        btnMakeBooking.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        btnMakeBooking.setContentAreaFilled(false);
        btnMakeBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeBookingActionPerformed(evt);
            }
        });

        lblStudentHomePage.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblStudentHomePage.setForeground(new java.awt.Color(45, 118, 232));
        lblStudentHomePage.setText("Book slot(s) for BASKETBALL COURT at MARINO CENTRE for :");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(45, 118, 232));
        jLabel1.setText("(Booking Date)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblStudentHomePage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMakeBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBookingHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbNumberOfPeople, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lblStudentHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbNumberOfPeople, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                .addComponent(btnMakeBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnBookingHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMakeBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeBookingActionPerformed
        String selected = cbNumberOfPeople.getSelectedItem().toString();
        LocalDate selectedDate = null;
        for (LocalDate localDate: availableDates) {
            if (localDate.toString().equals(selected)) {
                selectedDate = localDate;
                break;
            }
        }
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        rightPanel.add("StudentBookingJPanel", new StudentBookingJPanel(
                rightPanel, 
                userAccount, 
                enterprise, 
                business, 
                selectedDate));
        layout.next(rightPanel);
    }//GEN-LAST:event_btnMakeBookingActionPerformed

    private void btnBookingHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingHistoryActionPerformed
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        rightPanel.add("ViewBookingHistoryJPanel", new ViewBookingHistoryJPanel(
                rightPanel, 
                userAccount, 
                enterprise, 
                business));
        layout.next(rightPanel);
    }//GEN-LAST:event_btnBookingHistoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookingHistory;
    private javax.swing.JButton btnMakeBooking;
    private javax.swing.JComboBox<String> cbNumberOfPeople;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblStudentHomePage;
    // End of variables declaration//GEN-END:variables
}
