package Interface.MaintanenceRole;

import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author bboysticker
 * @author bochao
 */
public class ViewRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerSupportViewRequestJPanel
     */
    private JPanel rightPanel;
    private Enterprise enterprise;
    private WorkRequest workRequest;
    private DateFormat dateFormat;
    
    public ViewRequestJPanel(JPanel rightPanel, Enterprise enterprise, WorkRequest workRequest) {
        initComponents();
        this.rightPanel = rightPanel;
        this.enterprise = enterprise;
        this.workRequest = workRequest;
        this.dateFormat = DateFormat.getDateInstance();
        
        txtCustomerNotes.setEnabled(false);
        txtRequestDate.setEnabled(false);
        txtRequestID.setEnabled(false);
        txtSender.setEnabled(false);
        cbStatus.setEnabled(false);
        btnSave.setEnabled(false);
        
        populate();
    }
    
    private void populate() {
        int id = workRequest.getId();
        UserAccount sender = workRequest.getSender();
        String notes = workRequest.getMessage();
        Date date = workRequest.getRequestDate();
        String status = workRequest.getStatus().toString();
       
        txtCustomerNotes.setText(notes);
        txtRequestDate.setText(dateFormat.format(date));
        txtRequestID.setText(Integer.toString(id));
        txtSender.setText(sender.getEmployee().getName());
                
        cbStatus.addItem("Pending");
        cbStatus.addItem("Solved");
        
        if(status.equals("Pending")) cbStatus.setSelectedIndex(0);
        else if(status.equals("Solved")) cbStatus.setSelectedIndex(1);
        else{
            System.out.println("no status");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblRequestID = new javax.swing.JLabel();
        lblRequestDate = new javax.swing.JLabel();
        lblSender = new javax.swing.JLabel();
        lblCustomerNotes = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        txtRequestID = new javax.swing.JTextField();
        txtSender = new javax.swing.JTextField();
        txtCustomerNotes = new javax.swing.JTextField();
        txtRequestDate = new javax.swing.JTextField();
        cbStatus = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 900));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(45, 118, 232));
        jLabel1.setText("Request Details");

        lblRequestID.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblRequestID.setForeground(new java.awt.Color(45, 118, 232));
        lblRequestID.setText("Request ID:");

        lblRequestDate.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblRequestDate.setForeground(new java.awt.Color(45, 118, 232));
        lblRequestDate.setText("Request Date:");

        lblSender.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblSender.setForeground(new java.awt.Color(45, 118, 232));
        lblSender.setText("Sender:");

        lblCustomerNotes.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblCustomerNotes.setForeground(new java.awt.Color(45, 118, 232));
        lblCustomerNotes.setText("Customer Notes");

        lblStatus.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(45, 118, 232));
        lblStatus.setText("Status:");

        txtRequestID.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtRequestID.setEnabled(false);

        txtSender.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtSender.setEnabled(false);

        txtCustomerNotes.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtCustomerNotes.setEnabled(false);

        txtRequestDate.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtRequestDate.setEnabled(false);

        cbStatus.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        cbStatus.setEnabled(false);

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(45, 118, 232));
        btnUpdate.setText("Update");
        btnUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        btnUpdate.setContentAreaFilled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(45, 118, 232));
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        btnSave.setContentAreaFilled(false);
        btnSave.setEnabled(false);
        btnSave.setPreferredSize(new java.awt.Dimension(105, 30));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(45, 118, 232));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        btnBack.setContentAreaFilled(false);
        btnBack.setPreferredSize(new java.awt.Dimension(100, 40));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRequestID)
                                    .addComponent(lblSender)
                                    .addComponent(lblCustomerNotes)
                                    .addComponent(lblRequestDate))
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtRequestDate)
                                    .addComponent(txtCustomerNotes)
                                    .addComponent(txtSender)
                                    .addComponent(txtRequestID, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblStatus))))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRequestID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRequestID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSender))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustomerNotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomerNotes))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRequestDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRequestDate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        btnUpdate.setEnabled(false);
        btnSave.setEnabled(true);
        cbStatus.setEnabled(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        Component[] comps = this.rightPanel.getComponents();
        for (Component comp : comps) {
            if (comp instanceof MaintanenceHomePageJPanel) {
                MaintanenceHomePageJPanel panel = (MaintanenceHomePageJPanel) comp;
                panel.populate();
            }
        }
        layout.previous(rightPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String newStatus = cbStatus.getSelectedItem().toString();
        if (newStatus.equals("Solved")) {
            workRequest.setStatus(WorkRequest.Status.Solved);
            btnUpdate.setEnabled(true);
            btnSave.setEnabled(false);
            cbStatus.setEnabled(false);
        }
        else{
            JOptionPane.showMessageDialog(null, "Only can set status to solved", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCustomerNotes;
    private javax.swing.JLabel lblRequestDate;
    private javax.swing.JLabel lblRequestID;
    private javax.swing.JLabel lblSender;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtCustomerNotes;
    private javax.swing.JTextField txtRequestDate;
    private javax.swing.JTextField txtRequestID;
    private javax.swing.JTextField txtSender;
    // End of variables declaration//GEN-END:variables
}
