package Interface.CustomerSupportRole;

import Business.Employee.Employee;
import Business.Enterprise.FacilityEnterprise;
import Business.Role.MaintanenceRole;
import Business.ThatsMyPlaceSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Karti
 * @author bochao
 */
public class AddMaintenanceEmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddMaintenanceEmployeeJPanel
     */
    private JPanel rightPanel;
    private UserAccount userAccount;
    private FacilityEnterprise facilityEnterprise;
    private ThatsMyPlaceSystem business;
    
    public AddMaintenanceEmployeeJPanel(JPanel rightPanel, UserAccount userAccount, ThatsMyPlaceSystem business) {
        initComponents();
        this.rightPanel = rightPanel;
        this.userAccount = userAccount;
        this.business = business;
        
        if (userAccount == null) {
            // add new employee
            btnConfirm.setEnabled(true);
            
            txtEmployeeName.setEnabled(true);
            txtUsername.setEnabled(true);
            txtPassword.setEnabled(true);
        }
        else {
            populate();
        }
    }

    private void populate() {
        btnConfirm.setEnabled(true);
        
        txtEmployeeName.setText(userAccount.getEmployee().getName());
        txtUsername.setText(userAccount.getUsername());
        txtPassword.setEchoChar('*');
        
        txtEmployeeName.setEnabled(true);
        txtUsername.setEnabled(true);
        txtPassword.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmployeeDetails = new javax.swing.JLabel();
        lblEmployeeName = new javax.swing.JLabel();
        txtEmployeeName = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        lblPassowrd = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnConfirm = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 700));

        lblEmployeeDetails.setBackground(new java.awt.Color(255, 255, 255));
        lblEmployeeDetails.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lblEmployeeDetails.setForeground(new java.awt.Color(45, 118, 232));
        lblEmployeeDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmployeeDetails.setText("Add Employee");

        lblEmployeeName.setBackground(new java.awt.Color(255, 255, 255));
        lblEmployeeName.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblEmployeeName.setForeground(new java.awt.Color(45, 118, 232));
        lblEmployeeName.setText("Name:");

        txtEmployeeName.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtEmployeeName.setForeground(new java.awt.Color(45, 118, 232));
        txtEmployeeName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));

        lblUsername.setBackground(new java.awt.Color(255, 255, 255));
        lblUsername.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(45, 118, 232));
        lblUsername.setText("Username:");

        lblPassowrd.setBackground(new java.awt.Color(255, 255, 255));
        lblPassowrd.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblPassowrd.setForeground(new java.awt.Color(45, 118, 232));
        lblPassowrd.setText("Password:");

        txtUsername.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(45, 118, 232));
        txtUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));

        txtPassword.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(45, 118, 232));
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));

        btnConfirm.setBackground(new java.awt.Color(255, 255, 255));
        btnConfirm.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(45, 118, 232));
        btnConfirm.setText("Confirm");
        btnConfirm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        btnConfirm.setContentAreaFilled(false);
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(45, 118, 232));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        btnBack.setContentAreaFilled(false);
        btnBack.setPreferredSize(new java.awt.Dimension(100, 40));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEmployeeDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(313, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassowrd, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmployeeName)
                            .addComponent(txtUsername)
                            .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(287, 287, 287))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblEmployeeDetails)
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeName)
                    .addComponent(txtEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassowrd)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        String employeeName = txtEmployeeName.getText();
        String password = String.valueOf(txtPassword.getPassword());
        String userName = txtUsername.getText();
        
        Employee employee = business.getEmployeeDirectory().createEmployee(employeeName);
       
        business.getUserAccountDirectory().createUserAccount(userName, password, employee, new MaintanenceRole() );
 
        txtEmployeeName.setEnabled(false);
        txtUsername.setEnabled(false);
        txtPassword.setEnabled(false);
        btnConfirm.setEnabled(false);
        
        JOptionPane.showMessageDialog(null, "Added successfully!", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        Component[] comps = this.rightPanel.getComponents();
        for (Component comp : comps) {
            if (comp instanceof ManageMaintenanceEmployeeJPanel) {
                ManageMaintenanceEmployeeJPanel panel = (ManageMaintenanceEmployeeJPanel) comp;
                panel.populate();
            }
        }
        layout.previous(rightPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel lblEmployeeDetails;
    private javax.swing.JLabel lblEmployeeName;
    private javax.swing.JLabel lblPassowrd;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtEmployeeName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
