package Interface.CustomerSupportRole;

import Business.Booking.Booking;
import Business.Booking.MasterBookingList;
import Interface.MaintanenceRole.ViewRequestJPanel;
import Business.Enterprise.Enterprise;
import Business.Enterprise.FacilityEnterprise;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import static Business.Role.Role.RoleType.Student;
import Business.Student.Student;
import Business.ThatsMyPlaceSystem;
import Business.WorkQueue.CustomerSupportWorkRequest;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * All requests from user will come to Customer Support. That includes:
 *      1. Cleaning Request
 *      2. Maintenance Request
 *      3. Customer feedback
 *      4. etc.
 * 
 * Customer Support can manage all kinds of request in this panel. That includes:
 *      1. Change the status of booking request according to the definition of status.
 *      2. Redirect the maintenance requests to Maintenance Work Area.
 * 
 * @author bboysticker
 * @author bochao
 */
public class CustomerSupportHomePageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerSupportHomePageJPanel
     */
    private JPanel rightPanel;
    private Enterprise enterprise;
    private ThatsMyPlaceSystem business;
    private FacilityEnterprise newFacility; 
    
    public CustomerSupportHomePageJPanel(JPanel rightPanel, Enterprise enterprise, ThatsMyPlaceSystem business) {
        initComponents();
        this.rightPanel = rightPanel;
        this.enterprise = enterprise;
        this.business=business;
        this.newFacility = (FacilityEnterprise) business.getNetworkList()
                                                                .get(0)
                                                                .getEnterpriseDirectory()
                                                                .getEnterpriseList()
                                                                .get(0);
        
        populate();
    }
    
    public void populate(){
        List<Booking> list = newFacility.getMasterBookingList().getMasterBookingList();
        DefaultTableModel dtm = (DefaultTableModel)bookingList.getModel();
        dtm.setRowCount(0);

        for(Booking b : list){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0] = b.getRegistrant().getName();
            row[1] = b.getDate();
            row[2] = b;
            row[3] = b.getEndTime();
            row[4] = b.getStatus();
            dtm.addRow(row); 
        }
    }

    public void populate(List<Booking> list){
        DefaultTableModel dtm = (DefaultTableModel)bookingList.getModel();
        dtm.setRowCount(0);

        for(Booking b : list){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0] = b.getRegistrant().getName();
            row[1] = b.getDate();
            row[2] = b;
            row[3] = b.getEndTime();
            row[4] = b.getStatus();
            dtm.addRow(row); 
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bookingList = new javax.swing.JTable();
        lblBookingList = new javax.swing.JLabel();
        btnManageFeedback = new javax.swing.JButton();
        btnManageBooking = new javax.swing.JButton();
        btnManageMaintenance = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 700));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 400));

        bookingList.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        bookingList.setForeground(new java.awt.Color(45, 118, 232));
        bookingList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Booking Date", "Start Time", "End Time", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bookingList);
        if (bookingList.getColumnModel().getColumnCount() > 0) {
            bookingList.getColumnModel().getColumn(0).setResizable(false);
            bookingList.getColumnModel().getColumn(1).setResizable(false);
            bookingList.getColumnModel().getColumn(2).setResizable(false);
            bookingList.getColumnModel().getColumn(3).setResizable(false);
            bookingList.getColumnModel().getColumn(4).setResizable(false);
        }

        lblBookingList.setBackground(new java.awt.Color(255, 255, 255));
        lblBookingList.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblBookingList.setForeground(new java.awt.Color(45, 118, 232));
        lblBookingList.setText("Booking List");

        btnManageFeedback.setBackground(new java.awt.Color(255, 255, 255));
        btnManageFeedback.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnManageFeedback.setForeground(new java.awt.Color(45, 118, 232));
        btnManageFeedback.setText("Manage Feedback");
        btnManageFeedback.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        btnManageFeedback.setContentAreaFilled(false);
        btnManageFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFeedbackActionPerformed(evt);
            }
        });

        btnManageBooking.setBackground(new java.awt.Color(255, 255, 255));
        btnManageBooking.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnManageBooking.setForeground(new java.awt.Color(45, 118, 232));
        btnManageBooking.setText("Manage Booking");
        btnManageBooking.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        btnManageBooking.setContentAreaFilled(false);
        btnManageBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageBookingActionPerformed(evt);
            }
        });

        btnManageMaintenance.setBackground(new java.awt.Color(255, 255, 255));
        btnManageMaintenance.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnManageMaintenance.setForeground(new java.awt.Color(45, 118, 232));
        btnManageMaintenance.setText("Manage Maintenance Employee");
        btnManageMaintenance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        btnManageMaintenance.setContentAreaFilled(false);
        btnManageMaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMaintenanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnManageBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(btnManageMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManageFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblBookingList, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblBookingList)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFeedbackActionPerformed
        // TODO add your handling code here:
        ManageFeedbackJPanel panel = new ManageFeedbackJPanel(rightPanel, newFacility, business);
        
        rightPanel.add("ManageFeedbackJPanel", panel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_btnManageFeedbackActionPerformed

    private void btnManageBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageBookingActionPerformed
        // TODO add your handling code here:
   
        
        int selectedRow = bookingList.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row ","Information", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            Booking bo = (Booking) bookingList.getValueAt(selectedRow, 2);
            
            if(bo.getStatus().equals(Booking.Status.Canceled)){
                JOptionPane.showMessageDialog(null, "Booking is Canceled! No action can be performed!");
                return;
            }
            else{
            ViewBookingJPanel panel = new ViewBookingJPanel(rightPanel, enterprise, bo);
            rightPanel.add("ViewBookingJPanel", panel);
            CardLayout layout = (CardLayout) rightPanel.getLayout();
            layout.next(rightPanel);
        
            }
        }
    }//GEN-LAST:event_btnManageBookingActionPerformed

    private void btnManageMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMaintenanceActionPerformed
        // TODO add your handling code here:
        ManageMaintenanceEmployeeJPanel panel = new ManageMaintenanceEmployeeJPanel(rightPanel, enterprise, business);
        rightPanel.add("ManageMaintenanceEmployeeJPanel", panel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_btnManageMaintenanceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bookingList;
    private javax.swing.JButton btnManageBooking;
    private javax.swing.JButton btnManageFeedback;
    private javax.swing.JButton btnManageMaintenance;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBookingList;
    // End of variables declaration//GEN-END:variables
}
