/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CustomerSupportRole;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.FacilityEnterprise;
import Business.Enterprise.UniversityEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.ThatsMyPlaceSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Karti
 * @author bochao
 */
public class ManageMaintenanceEmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageMaintenanceEmployeeJPanel
     */
    private JPanel rightPanel;
    //private Enterprise enterprise;
    private ThatsMyPlaceSystem business;
 
    //private ArrayList<Employee> allEmployeeList;
    private ArrayList<UserAccount> userAccountList;
    private ArrayList<UserAccount> allUserAccountList;
    private ArrayList<UserAccount> searchList;
    
    
    public ManageMaintenanceEmployeeJPanel(JPanel rightPanel, Enterprise enterprise, ThatsMyPlaceSystem business) {
        initComponents();
        this.rightPanel = rightPanel;
        //this.enterprise = enterprise;
        this.business = business;
        
        this.userAccountList = new ArrayList<>();
        //this.allEmployeeList = business.getEmployeeDirectory().getEmployeeList();
        this.allUserAccountList = business.getUserAccountDirectory().getUserAccounts();
        
        
        
        populate();
    }
    
    
    public void populate() {
        this.allUserAccountList = business.getUserAccountDirectory().getUserAccounts();
        this.userAccountList.clear();
        for(UserAccount u : allUserAccountList){
            if(u.getRole().getName().equals("Maintanence"))
                userAccountList.add(u);
        }
        
        DefaultTableModel dtm = (DefaultTableModel) MaintenanceEmployeeList.getModel();
        dtm.setRowCount(0);
        
        for (UserAccount u : userAccountList) {
            Object[] row = new Object[dtm.getColumnCount()];
            
            row[0] = u.getEmployee().getId();
            row[1] = u.getEmployee().getName();
            row[2] = u;
            row[3] = 0;

            dtm.addRow(row);
        }
    }
    
    public void populate(ArrayList<UserAccount> list) {
        
        DefaultTableModel dtm = (DefaultTableModel) MaintenanceEmployeeList.getModel();
        dtm.setRowCount(0);
        
        for (UserAccount u : list) {
            Object[] row = new Object[dtm.getColumnCount()];
            
            row[0] = u.getEmployee().getId();
            row[1] = u.getEmployee().getName();
            row[2] = u;
            row[3] = u.getWorkQueue().getWorkRequestList().size();

            dtm.addRow(row);
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMaintenanceTeam = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MaintenanceEmployeeList = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        lblEmployeeID = new javax.swing.JLabel();
        txtEmployeeID = new javax.swing.JTextField();
        lblEmployeeName = new javax.swing.JLabel();
        txtEmployeeName = new javax.swing.JTextField();
        btnRemove = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 700));

        lblMaintenanceTeam.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblMaintenanceTeam.setForeground(new java.awt.Color(45, 118, 232));
        lblMaintenanceTeam.setText("Maintenance Team Support");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));

        MaintenanceEmployeeList.setForeground(new java.awt.Color(45, 118, 232));
        MaintenanceEmployeeList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Employee Name", "Username", "No Of Maintenance Requests"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(MaintenanceEmployeeList);
        if (MaintenanceEmployeeList.getColumnModel().getColumnCount() > 0) {
            MaintenanceEmployeeList.getColumnModel().getColumn(0).setResizable(false);
            MaintenanceEmployeeList.getColumnModel().getColumn(1).setResizable(false);
            MaintenanceEmployeeList.getColumnModel().getColumn(2).setResizable(false);
            MaintenanceEmployeeList.getColumnModel().getColumn(3).setResizable(false);
        }

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(45, 118, 232));
        btnSearch.setText("SEARCH");
        btnSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        btnSearch.setContentAreaFilled(false);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblEmployeeID.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblEmployeeID.setForeground(new java.awt.Color(45, 118, 232));
        lblEmployeeID.setText("Employee ID");

        txtEmployeeID.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        lblEmployeeName.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblEmployeeName.setForeground(new java.awt.Color(45, 118, 232));
        lblEmployeeName.setText("Employee Name");
        lblEmployeeName.setPreferredSize(new java.awt.Dimension(127, 35));

        txtEmployeeName.setPreferredSize(new java.awt.Dimension(10, 27));

        btnRemove.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(45, 118, 232));
        btnRemove.setText("REMOVE EMPLOYEE");
        btnRemove.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        btnRemove.setContentAreaFilled(false);
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(45, 118, 232));
        btnUpdate.setText("UPDATE EMPLOYEE");
        btnUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        btnUpdate.setContentAreaFilled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        addBtn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        addBtn.setForeground(new java.awt.Color(45, 118, 232));
        addBtn.setText("ADD MAINTENANCE EMPLOYEE");
        addBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        addBtn.setContentAreaFilled(false);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(45, 118, 232));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        btnBack.setContentAreaFilled(false);
        btnBack.setPreferredSize(new java.awt.Dimension(100, 40));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaintenanceTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblEmployeeID)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(37, 37, 37)
                                            .addComponent(lblEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(78, 78, 78)
                                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblMaintenanceTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEmployeeName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String name = txtEmployeeName.getText();
        String id = txtEmployeeID.getText();
        
        txtEmployeeName.setBorder(new LineBorder(new Color(128, 128, 128)));
        txtEmployeeID.setBorder(new LineBorder(new Color(128, 128, 128)));
        
        lblEmployeeID.setForeground(Color.BLACK);
        lblEmployeeName.setForeground(Color.BLACK);
        
        // If no input, return
        if (name.equals("") && id.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter something", "Warning", JOptionPane.WARNING_MESSAGE);
            txtEmployeeName.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtEmployeeID.setBorder(BorderFactory.createLineBorder(Color.RED));
            populate();
            return;
        }
        
        
        
        searchList = new ArrayList<>();
        boolean nameBool = true;
        boolean IdBool = true;
        for(UserAccount user : userAccountList){
            if(name.length() != 0){
                nameBool = name.equals(user.getEmployee().getName());
            }
            if(id.length() != 0){
                int intID = Integer.parseInt(id);
                IdBool = ( intID == user.getEmployee().getId());
            }
            
            if(  IdBool && nameBool) {              
                searchList.add(user);
            }
        }
       
        if (searchList.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No Result!", "Warning", JOptionPane.WARNING_MESSAGE);
            txtEmployeeID.setText("");
            txtEmployeeName.setText("");
            populate();
            
        }else{
            populate(searchList);
        }
        
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        int selectedRow = MaintenanceEmployeeList.getSelectedRow();
        if (selectedRow >= 0) {
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete?", "Warning", selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
                UserAccount useraccout = (UserAccount) MaintenanceEmployeeList.getValueAt(selectedRow, 2);
                business.getUserAccountDirectory().getUserAccounts().remove(useraccout);
                
                populate();
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select any row", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int selectedRow = MaintenanceEmployeeList.getSelectedRow();
        if (selectedRow >= 0) {
            UserAccount userAccount = (UserAccount) MaintenanceEmployeeList.getValueAt(selectedRow, 2);
            UpdateMaintenanceEmployeeJPanel panel = new UpdateMaintenanceEmployeeJPanel(rightPanel, userAccount, business);
            rightPanel.add("AddMaintenanceEmployeeJPanel", panel);
            CardLayout layout = (CardLayout) rightPanel.getLayout();
            layout.next(rightPanel);
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select any row", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        AddMaintenanceEmployeeJPanel panel = new AddMaintenanceEmployeeJPanel(rightPanel, null,  business);
        rightPanel.add("AddMaintenanceEmployeeJPanel", panel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_addBtnActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        layout.previous(rightPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MaintenanceEmployeeList;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblEmployeeName;
    private javax.swing.JLabel lblMaintenanceTeam;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtEmployeeName;
    // End of variables declaration//GEN-END:variables
}
