package Interface.FacilityAdminRole;

import Business.Enterprise.FacilityEnterprise;
import Business.Facility.Basketball.BasketballCourtAvailDirectory;
import Business.Facility.Basketball.BasketballCourtAvailability;
import Business.ThatsMyPlaceSystem;
import java.awt.CardLayout;
import java.awt.Component;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Karti
 * @author bochao
 */
public class ManageFacilityJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageFacilityJPanel
     */
    private JPanel rightPanel;
    private FacilityEnterprise facilityEnterprise;
    private ThatsMyPlaceSystem business;
    private BasketballCourtAvailDirectory basketballCourtAvailDirectory;
    private ArrayList<LocalDate> startTimeList;
    private ArrayList<LocalDate> endTimeList;
    private HashSet<LocalDate> availableDates;
    private int startTime;
    private int endTime;
    
    public ManageFacilityJPanel(JPanel rightPanel, FacilityEnterprise facilityEnterprise, ThatsMyPlaceSystem business) {
        initComponents();
        this.rightPanel = rightPanel;
        this.facilityEnterprise = facilityEnterprise;
        this.business = business;
      
        ComboBoxFrom.setEnabled(false);
        ComboBoxTo.setEnabled(false);
        txtNewEndTime.setEnabled(false);
        txtNewStartTime.setEnabled(false);
        
        btnSave.setEnabled(false);
        
        basketballCourtAvailDirectory = facilityEnterprise.getBasketballCourtAvailDirectory();
        startTimeList = new ArrayList<>();
        endTimeList = new ArrayList<>();
        availableDates = new HashSet<>();
        
        populate();
    }

    private void populate() {
        //get the first date
        List<BasketballCourtAvailability> availabilityList = basketballCourtAvailDirectory.getList();        
        for (BasketballCourtAvailability availability: availabilityList) {
            availableDates.add(availability.getDate());
        }
        
        ArrayList<LocalDate> localDateList = new ArrayList<>(availableDates);
        Collections.sort(localDateList);
        for (LocalDate localDate: localDateList) {
            ComboBoxFrom.addItem(localDate.toString());
            ComboBoxTo.addItem(localDate.toString());
        }
        
        txtNewStartTime.setText("");
        txtNewEndTime.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFacilityName = new javax.swing.JLabel();
        txtFacilityName = new javax.swing.JTextField();
        btnEditOperatingHours = new javax.swing.JButton();
        lblNewStartTime = new javax.swing.JLabel();
        lblNewEndTime = new javax.swing.JLabel();
        txtNewStartTime = new javax.swing.JTextField();
        txtNewEndTime = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        lblFromDate = new javax.swing.JLabel();
        lblToDate = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        ComboBoxFrom = new javax.swing.JComboBox<>();
        ComboBoxTo = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(100, 700));

        lblFacilityName.setBackground(new java.awt.Color(255, 255, 255));
        lblFacilityName.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblFacilityName.setForeground(new java.awt.Color(45, 118, 232));
        lblFacilityName.setText("Facility Name");

        txtFacilityName.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        txtFacilityName.setForeground(new java.awt.Color(45, 118, 232));
        txtFacilityName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFacilityName.setText("Basketball Court");
        txtFacilityName.setEnabled(false);

        btnEditOperatingHours.setBackground(new java.awt.Color(255, 255, 255));
        btnEditOperatingHours.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnEditOperatingHours.setForeground(new java.awt.Color(45, 118, 232));
        btnEditOperatingHours.setText("Edit Operating Hours");
        btnEditOperatingHours.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        btnEditOperatingHours.setContentAreaFilled(false);
        btnEditOperatingHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditOperatingHoursActionPerformed(evt);
            }
        });

        lblNewStartTime.setBackground(new java.awt.Color(255, 255, 255));
        lblNewStartTime.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblNewStartTime.setForeground(new java.awt.Color(45, 118, 232));
        lblNewStartTime.setText("New Start Time");

        lblNewEndTime.setBackground(new java.awt.Color(255, 255, 255));
        lblNewEndTime.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblNewEndTime.setForeground(new java.awt.Color(45, 118, 232));
        lblNewEndTime.setText("New End Time");

        txtNewStartTime.setEnabled(false);

        txtNewEndTime.setEnabled(false);

        lblDate.setBackground(new java.awt.Color(255, 255, 255));
        lblDate.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblDate.setForeground(new java.awt.Color(45, 118, 232));
        lblDate.setText("Date");

        lblFromDate.setBackground(new java.awt.Color(255, 255, 255));
        lblFromDate.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblFromDate.setForeground(new java.awt.Color(45, 118, 232));
        lblFromDate.setText("From");

        lblToDate.setBackground(new java.awt.Color(255, 255, 255));
        lblToDate.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblToDate.setForeground(new java.awt.Color(45, 118, 232));
        lblToDate.setText("To");

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(45, 118, 232));
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        btnSave.setContentAreaFilled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(45, 118, 232));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        btnBack.setContentAreaFilled(false);
        btnBack.setPreferredSize(new java.awt.Dimension(100, 40));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        ComboBoxFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxFromActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFacilityName, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(txtFacilityName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNewStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ComboBoxFrom, 0, 200, Short.MAX_VALUE)
                                            .addComponent(lblFromDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ComboBoxTo, 0, 200, Short.MAX_VALUE)
                                            .addComponent(lblToDate, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNewStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblNewEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNewEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(btnEditOperatingHours, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(187, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(399, 399, 399))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFacilityName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFacilityName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addComponent(btnEditOperatingHours, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFromDate)
                    .addComponent(lblToDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxTo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNewStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditOperatingHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditOperatingHoursActionPerformed
        ComboBoxFrom.setEnabled(true);
        ComboBoxTo.setEnabled(true);
        txtNewEndTime.setEnabled(true);
        txtNewStartTime.setEnabled(true);
        btnSave.setEnabled(true);
    }//GEN-LAST:event_btnEditOperatingHoursActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        LocalDate fromDate = LocalDate.parse(ComboBoxFrom.getSelectedItem().toString(), DateTimeFormatter.ISO_DATE);
        LocalDate endDate = LocalDate.parse(ComboBoxTo.getSelectedItem().toString(), DateTimeFormatter.ISO_DATE);
        
        if(fromDate.isAfter(endDate)){
            JOptionPane.showMessageDialog(null, "FromDate must earlier than toDate!!");
            return;
        }
        
        try{
            startTime = Integer.parseInt(txtNewStartTime.getText());
            endTime = Integer.parseInt(txtNewEndTime.getText());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Time must be a whole integer!!");
            return;
        }
        
        if(startTime >= endTime){
            JOptionPane.showMessageDialog(null, "Start Time must be less than End Time!!");
            return;
        }
        
        if(startTime >= 23 || endTime >= 23 || startTime <0 ||endTime <0 ){
            JOptionPane.showMessageDialog(null, "time range is 0-23");
            return;
        }
        
        for(BasketballCourtAvailability ba : basketballCourtAvailDirectory.getList()){
            LocalDate date = ba.getDate();
            int fromTime = ba.getStarTime();
            int toTime = ba.getEndTime();
            
            if( endDate.isBefore(date)  ||  fromDate.isAfter(date)){
                continue;
            }
            if( startTime <= fromTime   && toTime <= endTime){
                ba.change(false);
            }
        }
        
        ComboBoxFrom.setEnabled(false);
        ComboBoxTo.setEnabled(false);
        txtNewEndTime.setEnabled(false);
        txtNewStartTime.setEnabled(false);
        btnSave.setEnabled(false);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        rightPanel.remove(this);
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        Component[] comps = this.rightPanel.getComponents();
        for (Component comp : comps) {
            if (comp instanceof FacilityAdminHomePageJPanel) {
                FacilityAdminHomePageJPanel panel = (FacilityAdminHomePageJPanel) comp;
                panel.populate();
            }
        }
        layout.previous(rightPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void ComboBoxFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxFromActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxFrom;
    private javax.swing.JComboBox<String> ComboBoxTo;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEditOperatingHours;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblFacilityName;
    private javax.swing.JLabel lblFromDate;
    private javax.swing.JLabel lblNewEndTime;
    private javax.swing.JLabel lblNewStartTime;
    private javax.swing.JLabel lblToDate;
    private javax.swing.JTextField txtFacilityName;
    private javax.swing.JTextField txtNewEndTime;
    private javax.swing.JTextField txtNewStartTime;
    // End of variables declaration//GEN-END:variables
}
