package Interface.FacilityAdminRole;

import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Role.Role;
import Business.ThatsMyPlaceSystem;
import Business.UserAccount.UserAccount;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bochao
 */
public class ManageCustomerSupportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FacilityAdminJPanel
     */
    
    private JPanel rightPanel;
    private Enterprise enterprise;
    private ThatsMyPlaceSystem business;
    
    public ManageCustomerSupportJPanel(JPanel rightPanel, Enterprise enterprise, ThatsMyPlaceSystem business ) {
        initComponents();
        this.rightPanel = rightPanel;
        this.enterprise = enterprise;
        this.business = business;
        populate();
    }

    public void populate() {
        DefaultTableModel dtm = (DefaultTableModel) customerSupportJTable.getModel();
        dtm.setRowCount(0);
        
        ArrayList<UserAccount> userAccountList = business.getUserAccountDirectory().getUserAccounts();
        for (UserAccount ua: userAccountList) {
            if(ua.getRole().getName().equals("Customer Support")){
                Object[] row = new Object[dtm.getColumnCount()];
            
                row[0] = ua.getEmployee().getId();
                row[1] = ua.getEmployee();
                row[2] = ua;
                

                dtm.addRow(row);
            }
        }
    }
    
    private void populate(ArrayList<UserAccount> userAccounts) {
        DefaultTableModel dtm = (DefaultTableModel) customerSupportJTable.getModel();
        dtm.setRowCount(0);
        
        for (UserAccount ua: userAccounts) {
            if(ua.getRole().getName().equals("Customer Support")){
            
                Object[] row = new Object[dtm.getColumnCount()];
                row[0] = ua.getEmployee().getId();
                row[1] = ua.getEmployee();
                row[2] = ua;

                dtm.addRow(row);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerSupportJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblEmployeeName = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        lblEmployeeID = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 700));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(45, 118, 232));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        btnBack.setContentAreaFilled(false);
        btnBack.setPreferredSize(new java.awt.Dimension(100, 40));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 400));

        customerSupportJTable.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        customerSupportJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Employee Name", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(customerSupportJTable);
        if (customerSupportJTable.getColumnModel().getColumnCount() > 0) {
            customerSupportJTable.getColumnModel().getColumn(0).setResizable(false);
            customerSupportJTable.getColumnModel().getColumn(1).setResizable(false);
            customerSupportJTable.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(45, 118, 232));
        jLabel1.setText("Customer Support Summary");

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(45, 118, 232));
        btnSearch.setText("SEARCH");
        btnSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        btnSearch.setContentAreaFilled(false);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(45, 118, 232));
        btnUpdate.setText("UPDATE EMPLOYEE");
        btnUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        btnUpdate.setContentAreaFilled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblEmployeeName.setBackground(new java.awt.Color(255, 255, 255));
        lblEmployeeName.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblEmployeeName.setForeground(new java.awt.Color(45, 118, 232));
        lblEmployeeName.setText("Employee Name");

        lblEmployeeID.setBackground(new java.awt.Color(255, 255, 255));
        lblEmployeeID.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblEmployeeID.setForeground(new java.awt.Color(45, 118, 232));
        lblEmployeeID.setText("Employee ID");

        btnRemove.setBackground(new java.awt.Color(255, 255, 255));
        btnRemove.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(45, 118, 232));
        btnRemove.setText("REMOVE EMPLOYEE");
        btnRemove.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        btnRemove.setContentAreaFilled(false);
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(255, 255, 255));
        addBtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        addBtn.setForeground(new java.awt.Color(45, 118, 232));
        addBtn.setText("ADD CUSTOMER SUPPORT");
        addBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        addBtn.setContentAreaFilled(false);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(866, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEmployeeID)
                        .addGap(18, 18, 18)
                        .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblEmployeeName)
                        .addGap(18, 18, 18)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmployeeName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idTextField)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        rightPanel.remove(this);
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        layout.previous(rightPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String name = nameTextField.getText();
        String id = idTextField.getText();
        
         
        nameTextField.setBorder(new LineBorder(new Color(45,118,232)));
        idTextField.setBorder(new LineBorder(new Color(45,118,232)));
        
        lblEmployeeID.setForeground(new Color(45,118,232));
        lblEmployeeName.setForeground(new Color(45,118,232));
        
        // If no input, return
        if (name.equals("") && id.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter something", "Warning", JOptionPane.WARNING_MESSAGE);
            nameTextField.setBorder(BorderFactory.createLineBorder(Color.RED));
            idTextField.setBorder(BorderFactory.createLineBorder(Color.RED));
            populate();
            return;
        }
        
     
        int idInt = -1;
        if(id.length() != 0){
            try{
                idInt = Integer.parseInt(id);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Please enter Integer !", "Warning", JOptionPane.WARNING_MESSAGE);
                idTextField.setBorder(BorderFactory.createLineBorder(Color.RED));
                return;
            }
        }
        
        
        
        ArrayList<UserAccount> userAccountList = business.getUserAccountDirectory().getUserAccounts();
        ArrayList<UserAccount> newUserAccountList = new ArrayList<>();
        
        for (UserAccount ua: userAccountList) {
            boolean idBool = true;
            boolean nameBool = true;
            
            if(idInt != -1){
                idBool = (idInt == ua.getEmployee().getId() ? true : false);
            }
            if(name.length() != 0){
                nameBool = (name.equals(ua.getEmployee().getName()) ? true : false);
            }
            
            if( idBool  && nameBool){
                newUserAccountList.add(ua);
            }
            
        }
        
        if (newUserAccountList.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No Result!", "Warning", JOptionPane.WARNING_MESSAGE);
            idTextField.setText("");
            nameTextField.setText("");
            populate();
        }
        else {
            populate(newUserAccountList);
        }
        
        newUserAccountList.clear();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        int selectedRow = customerSupportJTable.getSelectedRow();
        if (selectedRow >= 0) {
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete?", "Warning", selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
                Employee employee = (Employee) customerSupportJTable.getValueAt(selectedRow, 1);
                UserAccount userAccount = (UserAccount) customerSupportJTable.getValueAt(selectedRow, 2);
                business.getEmployeeDirectory().getEmployeeList().remove(employee);
                business.getUserAccountDirectory().getUserAccounts().remove(userAccount);
                populate();
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select any row", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        ViewCustomerSupportJPanel panel = new ViewCustomerSupportJPanel(rightPanel, null, enterprise, business);
        rightPanel.add("AddCustomerSupportJPanel", panel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_addBtnActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int selectedRow = customerSupportJTable.getSelectedRow();
        if (selectedRow >= 0) {
            UserAccount ua = (UserAccount) customerSupportJTable.getValueAt(selectedRow, 2);
            ViewCustomerSupportJPanel panel = new ViewCustomerSupportJPanel(rightPanel, ua, enterprise, business);
            rightPanel.add("ViewCustomerSupportJPanel", panel);
            CardLayout layout = (CardLayout) rightPanel.getLayout();
            layout.next(rightPanel);
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select any row", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTable customerSupportJTable;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblEmployeeName;
    private javax.swing.JTextField nameTextField;
    // End of variables declaration//GEN-END:variables
}
