package Interface.UniversityAdminRole;

import Business.EmailUtil.EmailUtil;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Role.Role;
import Business.Role.StudentRole;
import Business.Student.Student;
import Business.ThatsMyPlaceSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.TimerTask;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Karti
 */
public class AddStudentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddStudentJPanel
     */
    private JPanel rightPanel;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private ThatsMyPlaceSystem business;
    
    public AddStudentJPanel(JPanel rightPanel, 
            UserAccount userAccount, 
            Enterprise enterprise, 
            ThatsMyPlaceSystem business) {
        initComponents();
        this.rightPanel = rightPanel;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.business = business;
        
        if (userAccount == null) {
            // add new employee
            
            
            txtName.setEnabled(true);
            txtName.setText("");
            txtUserName.setEnabled(true);
            txtUserName.setText("");
            txtPassword.setEnabled(true);
            txtPassword.setText("");
            txtEmail.setEnabled(true);
            txtEmail.setText("");
                   
        }
        else {//update view
            populate();
        } 
    }
    
    private void populate() {
        
        txtName.setText(userAccount.getEmployee().getName());
        txtUserName.setText(userAccount.getUsername());
        txtPassword.setEchoChar('*');
        Student s = (Student) userAccount.getEmployee();
        txtEmail.setText(s.getEmail());
        
        txtName.setEnabled(true);
        txtUserName.setEnabled(true);
        txtPassword.setEnabled(true);
        txtEmail.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStudentName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 700));

        lblStudentName.setBackground(new java.awt.Color(255, 255, 255));
        lblStudentName.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblStudentName.setForeground(new java.awt.Color(45, 118, 232));
        lblStudentName.setText("Student Name");

        txtName.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(45, 118, 232));
        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));

        lblUserName.setBackground(new java.awt.Color(255, 255, 255));
        lblUserName.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(45, 118, 232));
        lblUserName.setText("UserName");

        txtUserName.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(45, 118, 232));
        txtUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));

        lblPassword.setBackground(new java.awt.Color(255, 255, 255));
        lblPassword.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(45, 118, 232));
        lblPassword.setText("Password");

        btnAdd.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(45, 118, 232));
        btnAdd.setText("Add / Update");
        btnAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        btnAdd.setContentAreaFilled(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(45, 118, 232));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        btnBack.setContentAreaFilled(false);
        btnBack.setPreferredSize(new java.awt.Dimension(100, 40));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblEmail.setBackground(new java.awt.Color(255, 255, 255));
        lblEmail.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(45, 118, 232));
        lblEmail.setText("Email ID");

        txtEmail.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(45, 118, 232));
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(45, 118, 232));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Student");

        txtPassword.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(45, 118, 232));
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtPassword))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtEmail)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblStudentName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String name = txtName.getText();
        String username = txtUserName.getText();
        String password = txtPassword.getText();
        String email = txtEmail.getText();
        
        if(name.isEmpty()||name.equalsIgnoreCase("")){ //check name blank
            JOptionPane.showMessageDialog(null, "Invalid Name!");
            txtName.setBorder(BorderFactory.createLineBorder(Color.RED));
            lblStudentName.setForeground(Color.RED);
            return;
        }
        else if(username.isEmpty()||username.equalsIgnoreCase("")){ //check username blank
            JOptionPane.showMessageDialog(null, "Invalid Username!");
            txtUserName.setBorder(BorderFactory.createLineBorder(Color.RED));
            lblUserName.setForeground(Color.RED);
            return;
        }
        else if(password.isEmpty()||password.equalsIgnoreCase("")){ //check password blank
            JOptionPane.showMessageDialog(null, "Invalid Password!");
            txtPassword.setBorder(BorderFactory.createLineBorder(Color.RED));
            lblPassword.setForeground(Color.RED);
            return;
        }
        else if(!email.contains("@husky.neu.edu")){
            JOptionPane.showMessageDialog(null, "Only Huskies Allowed! Please enter a valid email in format of 'abc@husky.neu.edu'");
            txtEmail.setBorder(BorderFactory.createLineBorder(Color.RED));
            lblEmail.setForeground(Color.RED);
            return;
        }
        
        
        if (userAccount == null){ // add function
            for(Employee e: enterprise.getEmployeeDirectory().getEmployeeList()){
                if(name.equalsIgnoreCase(e.getName())){
                    JOptionPane.showMessageDialog(null, "Student Name already exists in system! Enter a unique name!");
                    txtName.setBorder(BorderFactory.createLineBorder(Color.RED));
                    lblStudentName.setForeground(Color.RED);
                    return;
                }
            }   
            for(UserAccount ua: enterprise.getUserAccountDirectory().getUserAccounts()){
                if(username.equalsIgnoreCase(ua.getUsername())){
                    JOptionPane.showMessageDialog(null, "Username already exists! Enter a unique username!");
                    txtUserName.setBorder(BorderFactory.createLineBorder(Color.RED));
                    lblUserName.setForeground(Color.RED);
                    return;
                }
            }    
            Student student = enterprise.getEmployeeDirectory().createStudent(name, email);
            StudentRole studentRole = new StudentRole();
            business.getUserAccountDirectory().createUserAccount(username, password, student, studentRole);

            new java.util.Timer().schedule(new TimerTask() {
                    @Override
                    public void run() {
                        System.out.println("Email Sending ... Booking been closed ...");
                        EmailUtil.GmailSender(
                                email, 
                                "Welcome to thatsMyPlace!", 
                                "Welcome new user to our platform! We look forward to serving you!"
                        );
                    }
               }, 200);
            JOptionPane.showMessageDialog(null, "Student added successfully!");
        }
        
        else{                   //update function
            for(UserAccount ua: business.getUserAccountDirectory().getUserAccounts()){
                if(ua.getEmployee().equals(userAccount.getEmployee())){
                continue;
                }
                if(ua.getEmployee().getName().equalsIgnoreCase(name)){
                    JOptionPane.showMessageDialog(null, "Student Name already exists in system! Enter a unique name!");
                    txtName.setBorder(BorderFactory.createLineBorder(Color.RED));
                    lblStudentName.setForeground(Color.RED);
                    return;
                }
               
                if(ua.getUsername().equalsIgnoreCase(username)){
                    JOptionPane.showMessageDialog(null, "Username already exists! Enter a unique username!");
                    txtUserName.setBorder(BorderFactory.createLineBorder(Color.RED));
                    lblUserName.setForeground(Color.RED);
                    return;
                }
            
            }
            userAccount.setUsername(username);
            userAccount.setPassword(password);
            Student student = (Student) userAccount.getEmployee();
            student.setName(name);
            student.setEmail(email);
           
            JOptionPane.showMessageDialog(null, "Student updated successfully!");
            
        }
            
                
        
        txtName.setText("");
        txtUserName.setText("");
        txtPassword.setText("");
        txtEmail.setText("");
        
        txtEmail.setBorder(BorderFactory.createLineBorder(new Color(45,118,232)));
        lblEmail.setForeground(new Color(45,118,232));
        txtName.setBorder(BorderFactory.createLineBorder(new Color(45,118,232)));
        lblStudentName.setForeground(new Color(45,118,232));
        txtPassword.setBorder(BorderFactory.createLineBorder(new Color(45,118,232)));
        lblPassword.setForeground(new Color(45,118,232));
        txtUserName.setBorder(BorderFactory.createLineBorder(new Color(45,118,232)));
        lblUserName.setForeground(new Color(45,118,232));
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        Component[] comps = this.rightPanel.getComponents();
        for (Component comp : comps) {
            if (comp instanceof ManageStudentJPanel) {
                ManageStudentJPanel panel = (ManageStudentJPanel) comp;
                panel.populate();
            }
        }
        layout.previous(rightPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
