/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.UniversityAdminRole;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.FacilityEnterprise;
import Business.Enterprise.UniversityEnterprise;
import static Business.Role.Role.RoleType.Student;
import Business.ThatsMyPlaceSystem;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Karti
 */
public class UniversityAdminHomePageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UniversityAdminHomePage
     */
    private JPanel rightPanel;
    private Enterprise enterprise;
    private ThatsMyPlaceSystem business;
    
    public UniversityAdminHomePageJPanel(JPanel rightPanel, Enterprise enterprise, ThatsMyPlaceSystem business) {
        initComponents();
        this.rightPanel = rightPanel;
        this.enterprise = enterprise;
        this.business=business;
        populate();
        
    }

    public void populate(){
        FacilityEnterprise facilityEnterprise = (FacilityEnterprise) business.getNetworkList().get(0).getEnterpriseDirectory().getEnterpriseList().get(0);
        int bookingCount = facilityEnterprise.getMasterBookingList().getMasterBookingList().size();
        
        txtTotalBookings.setText(String.valueOf(bookingCount));
           
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDashboard = new javax.swing.JLabel();
        lblTotalBookings = new javax.swing.JLabel();
        btnManageStudent = new javax.swing.JButton();
        txtTotalBookings = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 700));

        lblDashboard.setBackground(new java.awt.Color(255, 255, 255));
        lblDashboard.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(45, 118, 232));
        lblDashboard.setText("MY DASHBOARD");

        lblTotalBookings.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalBookings.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblTotalBookings.setForeground(new java.awt.Color(45, 118, 232));
        lblTotalBookings.setText("TOTAL NO OF STUDENT BOOKINGS NEXT 2 WEEKS");

        btnManageStudent.setBackground(new java.awt.Color(255, 255, 255));
        btnManageStudent.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnManageStudent.setForeground(new java.awt.Color(45, 118, 232));
        btnManageStudent.setText("MANAGE STUDENT");
        btnManageStudent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        btnManageStudent.setContentAreaFilled(false);
        btnManageStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStudentActionPerformed(evt);
            }
        });

        txtTotalBookings.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtTotalBookings.setForeground(new java.awt.Color(45, 118, 232));
        txtTotalBookings.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 118, 232)));
        txtTotalBookings.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(btnManageStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTotalBookings, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTotalBookings, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalBookings, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalBookings, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                .addComponent(btnManageStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStudentActionPerformed
        // TODO add your handling code here:
        ManageStudentJPanel panel = new ManageStudentJPanel(rightPanel, enterprise, business);
        rightPanel.add("ManageStudentJPanel", panel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_btnManageStudentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageStudent;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblTotalBookings;
    private javax.swing.JTextField txtTotalBookings;
    // End of variables declaration//GEN-END:variables
}
